[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
from = "/*"
  to = "https://google.com"
  status = 200
  force = true
  signed = "SECRET"
 
