[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
  

[[redirects]]
  from = "/about"
  to = "https://friendly-lalande-764f5f.netlify.com/"
  status = 200
  force = true # COMMENT: ensure that we always redirect

