[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
  
  [context.staging.environment]
  ACCESS_TOKEN = "staging_key"
  

  
  [[redirects]]
  from = "/Products"
  to = "https://enik7akibz28.x.pipedream.net/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"} # COMMENT: add this header to the search request
  signed = ACCESS_TOKEN # COMMENT: sign each request with the value of this env variable


  
